slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    odom_frame:  odom_link
    map_frame:   map
    base_frame:  base_link
    scan_topic:  /laser_scan
    mode:        mapping          # ←  “localization” cuando ya tengas mapa
    enable_interactive_mode: true # panel RViz
    ## rangos de tu Lidar
    min_laser_range: 0.07
    max_laser_range: 5.0
    resolution:   0.05
    publish_period_sec: 1.0
    use_sim_time: true

