amcl:
  ros__parameters:
    use_sim_time: true
    min_particles: 500
    max_particles: 2000
    laser_model_type: likelihood_field
    tf_broadcast: true
    odom_frame_id: odom_link
    base_frame_id: base_link
    scan_topic: /laser_scan

map_server:
  ros__parameters:
    use_sim_time: true          # se sobrescribe con SLAM

bt_navigator:
  ros__parameters:
    use_sim_time: true

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins:    ["goal_checker"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      plugin_names: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: laser
        laser:
          topic: /laser_scan
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_link
      plugin_names: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

